name: Generate release

on:
  release:
    types: [ published ]

jobs:
  assemble:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        fetch-depth: '0'

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Apply gradle dependencies caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug version
        run: ./gradlew assembleDebug

      - name: Build release version
        run: ./gradlew assembleRelease

      - name: Upload the artifacts
          uses: skx/github-action-publish-binaries@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: '**/app/build/outputs/apk/**.apk'
